### ISSUE TITLE
How to add applications developed with flet to galleries or application examples

### ISSUE THREAD

**Issue by modaye** [flet-dev/gallery#1]
This is my program

Realized the display and search function of flip icon
![image](https://user-images.githubusercontent.com/44232619/190840765-6b434b3d-e35e-48b5-821e-50094bf49ad9.png)

[github Portal](https://github.com/modaye/Flet-Icon)

**Comment by FeodorFitsner** [comment]
You can add your example here (for now) while Gallery is being developed: https://github.com/flet-dev/examples/tree/main/python/community
